name:                cswk-program
version:             0.1.0.0

extra-source-files:
- report.org
- notes.org

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- text
- text-conversions
- containers
- transformers

library:
  source-dirs: src

executables:
  cswk-program-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cswk-program

tests:
  cswk-program-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cswk-program

default-extensions:
  - OverloadedStrings
